org.gradle.jvmargs=-Xmx768M -XX:MaxMetaspaceSize=256M -XX:+UseSerialGC
org.gradle.java.home=c:/Users/Avelc/.antigravity-ide/extensions/redhat.java-1.56.0-win32-x64/jre/21.0.12.1-win32-x86_64
org.gradle.parallel=false
org.gradle.vfs.watch=false

# Fabric / Minecraft versions (1.21.1 line)
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10
fabric_version=0.107.0+1.21.1

# Mod
mod_version=0.3.0-dev+1.21.1
maven_group=dev.puffspark.lightframe
archives_base_name=lightframe
